### ISSUE TITLE
LUA error when getting honor in open world

### ISSUE THREAD

**Issue by Epsynus** [LeoMelnyk/BGHistorian#2]
When I get honor in the open world, be it from killing Alliance or doing objectives such as in Sillithus, it throws the following error:

 ```
2x BGHistorian\BGHistorian-0.8.0.lua:91: attempt to perform arithmetic on field 'honorGained' (a nil value)
[string "@BGHistorian\BGHistorian-0.8.0.lua"]:91: in function `?'
[string "@Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Accountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
 ```

Based on my rudimentary understanding this seems to be a compatibility issue when run together with the Accountant Classic addon. I have forgotten to test it with Accountant disabled but can do that and get back to you if you want.

Would it be possible to resolve this incompatibility?

**Comment by LeoMelnyk** [comment]
0.8.1 should have the fix for this, thanks for reporting it!

**Comment by Epsynus** [comment]
Can confirm it is fixed with the newest version! Thanks so much!
